- .github/workflows/deploy-page.yml
- config.yml
#14 Made some changes that needed a required setting in the yaml, with out a fallback value
> Fix build?

- layouts/partials/custom/above-header.html
> Fix links to other LSIO sites

- i18n/en.yaml
- layouts/_default/list.html
Removes https://github.com/cstate/cstate/blob/master/layouts/_default/list.html#L39-L42
Change state banner text
> Layout and text changes

- content/issues/2021-11-12-emulatorjs.md
> add emulatorjs cstate

- content/issues/2022-05-22-lscr.md
> Close lscr issue

- content/issues/2022-08-08-fail2ban.md
- content/issues/2022-08-09-fail2ban.md
Pending https://github.com/linuxserver/docker-fail2ban/pull/1
> fail2ban release

- content/issues/2022-08-20-nginx-base.md
- content/issues/2022-10-14-photoshow.md
- content/issues/2022-10-14-pixapop.md
https://github.com/linuxserver/docker-photoshow/pull/30
https://github.com/linuxserver/docker-pixapop/pull/12
> Deprecate PhotoShow and Pixapop

- content/issues/2022-11-27-nzbget.md
Ready to merge now
Future PR: https://github.com/linuxserver/cstate/pull/137
> Create  2022-11-27-nzbget.md

- content/issues/2023-02-11-your_spotify.md
Wait for https://github.com/linuxserver/docker-your_spotify to build and push and be made public
> Release your_spotify

- content/issues/2023-05-06-armhf.md
> armhf reminder (May)

- content/issues/2023-05-28-mariadb.md
- content/issues/2023-05-29-mariadb.md
Ref: https://github.com/linuxserver/docker-mariadb/pull/124
> Known Issue: MariaDB Check and Repair

- content/issues/2023-06-06-armhf.md
> armhf reminder (June)

- content/issues/2023-07-01-armhf.md
> Kill armhf

- content/issues/2023-08-07-kavita.md
pending merge of https://github.com/linuxserver/docker-kavita/pull/1
> Release Kavita

- content/issues/2023-11-01-cron.md
- content/issues/2023-11-02-cron.md
Follow up from https://github.com/linuxserver/cstate/pull/174 and https://github.com/linuxserver/cstate/pull/180
To be merged on 2023-11-01
> standard cron live notice 2023-11-01

- config.yml
- layouts/partials/custom/meta.html
Adds opengraph, twitter and facebook metatags for embeding
> Meta tags!

- content/issues/2023-11-26-bambustudio.md
> Bambu Studio

- content/issues/2023-11-26-orcaslicer.md
> Orca Slicer

- content/issues/2024-01-01-unifi-controller.md
Obviously don't merge yet, just prepping for EOY.
> Deprecate unifi-controller

- content/issues/2024-02-03-zotero.md
- content/issues/2024-03-01-zotero.md
> add zotero cstate

- content/issues/2024-02-10-speedtest-tracker.md
https://github.com/linuxserver/docker-speedtest-tracker/pull/4
> Add Speedtest Tracker

- content/issues/2024-04-11-freetube-keepassxc-ardour-librewolf.md
- content/issues/2024-04-13-freetube-keepassxc-ardour-librewolf.md
> Release FreeTube KeePassXC Ardour Librewolf

- content/issues/2024-04-28-spotube.md
> add spotube cstate

- content/issues/2024-07-22-kali.md
Cstate for Kali Linux container 
https://github.com/linuxserver/docker-kali-linux
> add cstate for kali linux

- content/issues/2024-07-26-rust-ungoogled.md
Two new containers just built.
> add cstate for rustdesk and ungoogled-chromium

- content/issues/2025-02-19-snapdrop.md
Ignore the obviously incorrect commit message
> Deprecate Snapdrop

- content/issues/2025-06-19-dolphin.md
> add dolphin cstate

- content/issues/2025-06-25-xemu.md
> add xemu cstate

- content/issues/2025-06-25-flycast.md
> flycast container

- content/issues/2025-06-25-rpcs3.md
> cstate for RPCS3

- content/issues/2025-07-15-dogwalk.md
> dogwalk cstate

- content/issues/2025-08-10-onlyoffice.md
> onlyoffice cstate

- content/issues/2025-08-20-joplin.md
Title, new container for Joplin.
> joplin cstate

- content/issues/2025-08-26-scummvm.md
> add scummvm cstate

- content/issues/2025-09-07-vivaldi.md
- content/issues/2025-09-12-vivaldi.md
> vivaldi cstate
